.PHONY: runserver makemigrations migrate
runserver :
	python manage.py runserver --settings=COLLAB_DOC.local_settings
makemigrations :
	python manage.py makemigrations --settings=COLLAB_DOC.local_settings
migrate :
	python manage.py migrate --settings=COLLAB_DOC.local_settings