# Generated by Django 4.2.7 on 2023-12-18 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('versao', models.BigIntegerField(default=0)),
                ('conteudo', models.TextField()),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
            },
        ),
    ]
